export const documentariesData = [
  {
    id: "oceans",
    type: "documentaries",
    category: "História Natural",
    label: "Oceanos (Océans)",
    shortDescription: "Uma jornada cinematográfica pelas maravilhas e perigos dos cinco oceanos da Terra.",
    longDescription: "Filmado ao longo de vários anos com tecnologia de ponta, 'Océans' mergulha o espectador na vida marinha de uma forma raramente vista. O documentário foca menos na narração e mais na experiência visual imersiva, questionando o impacto da humanidade sobre as criaturas oceânicas.",
    videoUrl: "https://www.youtube.com/embed/9EpwPXxNKYA?&mute=1",
    imageUrl: "https://static.qobuz.com/images/covers/04/81/0884977488104_600.jpg",
    rating: "4.7",
    director: "Jacques Perrin & Jacques Cluzaud",
    releaseYear: 2010,
    secondaryImages: [],
    castAndCrew: [
      { name: "Pierce Brosnan", role: "Narrador (versão inglesa)", photo: "/src/assets/images/pierce-brosnan.jpg" },
      { name: "Jacques Perrin", role: "Narrador (versão francesa)", photo: "/src/assets/images/jacques-perrin.jpg" },
    ],
    tags: ["Cinematografia", "Vida Selvagem", "Natureza"],
    icon: "🎥",
    duration: "1h 44min",
    location: {
      name: "Oceanos do Mundo Inteiro",
      description: "Filmado em mais de 50 locais diferentes, desde as costas da Galápagos até os mares gelados do Ártico.",
    },
    relatedContent: {
      fauna: [
        { label: "Baleia Jubarte", id: "baleia-jubarte" },
        { label: "Tubarão-Branco", id: "tubarao-branco" },
      ],
      flora: [],
    },
  },
  {
    id: "em-busca-dos-corais",
    type: "documentaries",
    category: "Conservação",
    label: "Em Busca dos Corais",
    shortDescription: "Mergulhadores e cientistas investigam o desaparecimento em massa dos recifes de coral.",
    longDescription: "Uma equipe de cinegrafistas e cientistas se une para documentar o alarmante fenômeno do branqueamento de corais. Eles enfrentam desafios técnicos para desenvolver a primeira câmera time-lapse capaz de registrar o processo, revelando a devastação causada pelo aquecimento dos oceanos e fazendo um apelo urgente à ação.",
    videoUrl: "https://www.youtube.com/embed/b6fHA9R2cKI?&mute=1",
    imageUrl: "https://th.bing.com/th/id/R.e2f37fbbbce7c870888015e38281a537?rik=dEYSm28H9IEikA&pid=ImgRaw&r=0",
    rating: "4.8",
    director: "Jeff Orlowski",
    releaseYear: 2017,
    secondaryImages: [],
    castAndCrew: [
      { name: "Zack Rago", role: "Técnico de Câmera e Biólogo", photo: "/src/assets/images/zack-rago.jpg" },
      { name: "Dr. J.E.N. Veron", role: "Cientista Chefe", photo: "/src/assets/images/jen-veron.jpg" },
    ],
    tags: ["Mudanças Climáticas", "Conservação", "Oceanografia"],
    icon: "🎥",
    duration: "1h 29min",
    location: {
      name: "Recifes de Coral Globais",
      description: "As filmagens ocorrem em diversos locais, incluindo a Grande Barreira de Corais na Austrália e recifes no Havaí e Bahamas.",
    },
    relatedContent: {
      fauna: [{ label: "Peixe-Palhaço", id: "peixe-palhaco" }],
      flora: [{ label: "Recifes de Coral", id: "recifes-de-coral" }],
    },
  },
  {
    id: "professor-polvo",
    type: "documentaries",
    category: "Biologia Marinha",
    label: "Professor Polvo",
    shortDescription: "Um cineasta cria um laço surpreendente com um polvo em uma floresta de kelp na África do Sul.",
    longDescription: "Vencedor do Oscar, este documentário segue o cineasta Craig Foster, que estabelece uma relação de confiança com um polvo fêmea. Ele documenta a curta e extraordinária vida do animal, suas táticas de caça, sua incrível inteligência e sua luta pela sobrevivência, revelando uma conexão profunda entre humanos e a natureza.",
    videoUrl: "https://www.youtube.com/embed/3s0LTDhqe5A?&mute=1",
    imageUrl: "https://s2.glbimg.com/UEMqCHT2ScAiLbHvJx0ppKTGBEQ=/smart/e.glbimg.com/og/ed/f/original/2021/04/21/professorpolvoposter.jpg",
    rating: "4.9",
    director: "Pippa Ehrlich & James Reed",
    releaseYear: 2020,
    secondaryImages: [],
    castAndCrew: [
      { name: "Craig Foster", role: "Naturalista e Protagonista", photo: "/src/assets/images/craig-foster.jpg" },
    ],
    tags: ["Natureza", "Biologia", "Conservação"],
    icon: "🎥",
    duration: "1h 25min",
    location: {
      name: "Floresta de Kelp, África do Sul",
      description: "Filmado nas águas frias e ricas em biodiversidade da costa da Cidade do Cabo, África do Sul.",
    },
    relatedContent: {
      fauna: [{ label: "Polvo-Comum", id: "polvo-comum" }],
      flora: [{ label: "Alga Kelp", id: "alga-kelp" }],
    },
  },
  {
    id: "mission-blue",
    type: "documentaries",
    category: "Conservação",
    label: "Mission Blue",
    shortDescription: "A jornada da lendária oceanógrafa Sylvia Earle para salvar os oceanos da Terra.",
    longDescription: "Este documentário traça a vida e a carreira da Dra. Sylvia Earle, uma pioneira da exploração submarina. Ele destaca sua campanha global para criar uma rede de áreas marinhas protegidas, chamadas de 'Hope Spots' (Pontos de Esperança), para proteger os oceanos das maiores ameaças que enfrentam.",
    videoUrl: "https://www.youtube.com/embed/B1wp2MQCsfQ?&mute=1",
    imageUrl: "https://www.tribute.ca/news/wp-content/uploads/2020/07/MISSION-BLUE-650x436.jpg",
    rating: "4.7",
    director: "Robert Nixon & Fisher Stevens",
    releaseYear: 2014,
    secondaryImages: [],
    castAndCrew: [
      { name: "Dr. Sylvia Earle", role: "Protagonista e Oceanógrafa", photo: "/src/assets/images/sylvia-earle.jpg" },
      { name: "James Cameron", role: "Participação", photo: "/src/assets/images/james-cameron.jpg" },
    ],
    tags: ["Ativismo", "Conservação", "Biologia Marinha"],
    icon: "🎥",
    duration: "1h 34min",
    location: {
      name: "Global",
      description: "Acompanha a Dra. Earle em suas viagens por todo o mundo, desde as Ilhas Galápagos até os corais da Austrália.",
    },
    relatedContent: {
      fauna: [{ label: "Tubarão-Baleia", id: "tubarao-baleia" }],
      flora: [],
    },
  },
  {
    id: "jago-a-life-underwater",
    type: "documentaries",
    category: "Cultura",
    label: "Jago: Uma Vida Subaquática",
    shortDescription: "A história de um caçador submarino de 80 anos do povo Bajau, que mergulha em apneia.",
    longDescription: "Um retrato íntimo e poético de Rohani, um mestre caçador do povo Bajau da Indonésia, que passa a vida mergulhando nas profundezas com uma única inspiração. O filme explora sua conexão espiritual com o oceano, as tradições de seu povo e as memórias que moldaram sua vida sob as ondas.",
    videoUrl: "https://www.youtube.com/embed/Tp-7oZMOC9k?&mute=1",
    imageUrl: "https://m.media-amazon.com/images/S/pv-target-images/fd6b7b0de878a4af1d228b56755f7fc0310df10c17496dc98c4d58d8782cfafe.jpg",
    rating: "4.6",
    director: "James Reed & James Morgan",
    releaseYear: 2015,
    secondaryImages: [],
    castAndCrew: [
      { name: "Rohani", role: "Caçador Submarino", photo: "/src/assets/images/rohani.jpg" },
    ],
    tags: ["Cultura", "Apneia", "Indonésia"],
    icon: "🎥",
    duration: "48min",
    location: {
      name: "Arquipélago de Togian, Indonésia",
      description: "Filmado na comunidade nômade marítima dos Bajau, conhecida por suas habilidades de mergulho livre.",
    },
    relatedContent: {
      fauna: [],
      flora: [{ label: "Recifes de Coral", id: "recifes-de-coral" }],
    },
  },
  {
    id: "oceanos-de-plastico",
    type: "documentaries",
    category: "Meio Ambiente",
    label: "Oceanos de Plástico",
    shortDescription: "Uma investigação global sobre o impacto devastador do lixo plástico em nossos mares.",
    longDescription: "O que começa como a busca de um jornalista pela baleia-azul o leva a descobrir uma alarmante verdade: o oceano está repleto de lixo plástico. O documentário expõe a ciência por trás do problema, os efeitos na vida marinha e as consequências para a saúde humana, além de explorar soluções tecnológicas e políticas.",
    videoUrl: "https://www.youtube.com/embed/6zrn4-FfbXw?&mute=1",
    imageUrl: "https://watchdocumentaries.com/wp-content/uploads/a-plastic-ocean.jpg",
    rating: "4.8",
    director: "Craig Leeson",
    releaseYear: 2016,
    secondaryImages: [],
    castAndCrew: [
      { name: "Craig Leeson", role: "Jornalista", photo: "/src/assets/images/craig-leeson.jpg" },
      { name: "Tanya Streeter", role: "Mergulhadora e Ativista", photo: "/src/assets/images/tanya-streeter.jpg" },
    ],
    tags: ["Poluição", "Meio Ambiente", "Ativismo"],
    icon: "🎥",
    duration: "1h 42min",
    location: {
      name: "Global",
      description: "Filmado em mais de 20 locais ao redor do mundo para mostrar a escala global do problema do plástico.",
    },
    relatedContent: {
      fauna: [{ label: "Tartaruga-Marinha", id: "tartaruga-marinha" }],
      flora: [],
    },
  },
  {
    id: "the-blue-planet",
    type: "documentaries",
    category: "História Natural",
    label: "O Planeta Azul (The Blue Planet)",
    shortDescription: "A série original da BBC que redefiniu os documentários sobre a vida marinha.",
    longDescription: "A primeira série abrangente sobre a história natural dos oceanos do mundo. Narrada por David Attenborough, 'O Planeta Azul' levou os espectadores a uma jornada desde as costas familiares até as misteriosas profundezas, usando técnicas de filmagem inovadoras para a época para capturar o comportamento animal de maneiras nunca antes vistas.",
    videoUrl: "https://www.youtube.com/embed/wLYCPzdcZtk?&mute=1",
    imageUrl: "https://i.ytimg.com/vi/wLYCPzdcZtk/maxresdefault.jpg",
    rating: "5.0",
    director: "Alastair Fothergill",
    releaseYear: 2001,
    secondaryImages: [],
    castAndCrew: [
      { name: "David Attenborough", role: "Narrador", photo: "/src/assets/images/david-attenborough.jpg" },
    ],
    tags: ["Clássico", "Vida Selvagem", "BBC"],
    icon: "🎥",
    duration: "Série (8 episódios)",
    location: {
      name: "Oceanos do Mundo Inteiro",
      description: "Uma produção monumental que cobriu todos os aspectos dos habitats marinhos ao redor do globo.",
    },
    relatedContent: {
      fauna: [
        { label: "Baleia Jubarte", id: "baleia-jubarte" },
        { label: "Tubarão-Branco", id: "tubarao-branco" },
      ],
      flora: [{ label: "Fitoplâncton", id: "fitoplancton" }],
    },
  }
];